#!/bin/bash


# strict mode:
set -e
set -u
set -o pipefail

# activating a pyenv
python_dir="$HOME/projects/python" 

if [[ -d $python_dir/$1 ]]; then
    cd $python_dir/$1
    source $python_dir/$1/bin/activate
else
    echo "not a virtual environment"
fi

