#!/usr/bin/env python
# -*- coding: utf-8 -*-

import xmltodict
from urllib.request import urlopen

with urlopen('http://xml.buienradar.nl/') as xml:
    d = xmltodict.parse(xml)

    root = d['buienradarnl']
    data = root['weergegevens']
    print(data['verwachting_vandaag']['samenvatting'])
