#!/bin/bash

pushlog=~/files/autopush.log
log_prefix=$(date "+%d-%m-%Y %T"):

# repos=(".dotfiles bin projects/ellipsis projects/c/modern_approach")
repos=()
while IFS= read -r line; do
    repos+=($line)
done < /home/niels/.autopushrc

echo $log_prefix >> "$pushlog"
echo "==============================================" >> "$pushlog"
for repo in ${repos[@]}; do
    echo "" >> "$pushlog"
    echo "Repository: $repo" >> "$pushlog"
    (
        cd "$HOME/$repo"
        git pull
        git add --all
        git add --update
        git commit -m "autopush $(date "+%d-%m-%Y %T")" >> "$pushlog"
        git push >/dev/null 2>&1
        
    )
    echo "" >> "$pushlog"
    echo "==============================================" >> "$pushlog"
    echo "" >> "$pushlog"
done


