#!/bin/bash

logfile=~/files/autopush.log
date=$(date "+%d-%m-%Y %T"):

log_date() {
    echo "$date - $1" >> "$logfile"
}

log() {
    echo "pull - $1" >> "$logfile"
}

repos=()
while IFS= read -r line; do
    repos+=($line)
done < /home/niels/.autopushrc

for repo in ${repos[@]}; do
    log_date "Repository: $repo"
    (
        log $(git pull | grep -E "\|.*[0-9]* [+-]*" | awk '{print $1}')
        git add --all
        git add --update
        log $(git commit -m "autopush $(date "+%d-%m-%Y %T")" | sed -n 's/^[ ]*//;2p')
        git push >/dev/null 2>&1
    )
done


