#! /usr/bin/bash

BAT=${1:-BAT0}

low=10
interval=60

while true; do
    state=$(cat /sys/class/power_supply/"$BAT"/status)
    capacity=$(cat /sys/class/power_supply/"$BAT"/capacity)
    sleep "$interval"s

    if [[ "$capacity" -lt "$low" ]]; then
        if [[ "$state" -eq "Discharging" ]]; then
            notify-send  -u critical -a "Warning" "battery at $capacity%, better find a charger"
            interval=10
        else
            interval=60
        fi
    fi
done
