#! /usr/bin/bash

BAT=${1:-BAT0}

low=10

while true; do
    state=$(cat /sys/class/power_supply/"$BAT"/status)
    capacity=$(cat /sys/class/power_supply/"$BAT"/capacity)
    sleep 60s

    if [[ "$capacity" -lt "$low" ]]; then
            notify-send  -u critical -a "Warning" "battery at $capacity%, better find a charger"
    fi
done
