#!/bin/bash

SLEEP=5

while true; do
    FULL=$(</sys/class/power_supply/BAT0/energy_full_design)
    NOW=$(</sys/class/power_supply/BAT0/energy_now)
    BATTERY_LEVEL=$(echo "scale=2; $NOW/$FULL" | bc)

    if [[ -n $(acpi -b | grep "Discharging") ]]; then
        case $BATTERY_LEVEL in
            .30 ) notify-send -a "Battery" --urgency=LOW "at ${Battery}%"
                SLEEP=10
                ;;
            .20 ) notify-send -a "Battery" --urgency=CRITICAL "at ${Battery}%"
                SLEEP=5
                ;;
            .10 ) notify-send -a "Battery" --urgency=CRITICAL "at ${Battery}%"
                SLEEP=1
                ;;
        esac
    fi

    sleep ${SLEEP}m

done

# alt. approach:

# if [[ $BATTERY_LEVEL > .30 ]]; then
#     sleep 10m
# else
#     sleep 5m
#     if [[ $BATTERY_LEVEL <= .20 ]]; then
#         sleep 2m
#     fi
#     if [[ $BATTERY_LEVEL <= .10 ]]; then
#         sleep 1m
#     fi
# fi
