#!/bin/bash

usage() {
    echo
    echo "$(basename $0) [-gh] [-gl] [-a] [-bb] [--ssh]"
    echo
    echo "-gh       github"
    echo "-gl       gitlab"
    echo "-a        aur"
    echo "--ssh     use ssh (default https)"
    echo
    exit 1
}

[[ "$#" -lt 1 ]] && usage

delim="/"

while (( "$#" )); do

    case $1 in
        -gh )
            url="https://www.github.com"
            platform="hub"
            ;;
        -gl )
            url="https://www.gitlab.com"
            platform="lab"
            ;;
        --ssh )
            url="git@git${platform}.com"
            delim=":" ;;
        -a )
            url="https://aur.archlinux.org"
            delim="/"
            ;;
        * )
            repo="$1"
            ;;
    esac

    shift

done

git clone "${url}${delim}${repo}"
