#!/bin/bash

# see http://redsymbol.net/articles/unofficial-bash-strict-mode/
# set -e
# set -u
# set -o pipefail


case $3 in
    --ssh ) url=git@git
            delim=: ;;
    *) url=https://git
        delim=/ ;;
esac

case $1 in
    -gh ) git clone ${url}hub.com${delim}$2 ;;
    -gl ) git clone ${url}lab.com${delim}$2 ;;
    -a ) git clone https://aur.archlinux.org/$2 ;;
    -bb ) git clone https://bitbucket.org/$2 ;;
    *) echo "-g(ithub) -a(ur.archlinux.org) -bb(itbucket) --ssh" ;;
esac
