#!/bin/bash

usage() {
    echo
    echo "$(basename $0) [-gh] [-gl] [-a] [-bb] [--ssh]"
    echo
    echo "-h       github"
    echo "-l       gitlab"
    echo "-a       aur"
    echo "--ssh    use ssh (default https)"
    echo
    exit 1
}

[[ "$#" -lt 1 ]] && usage

while (( "$#" )); do

    case $1 in
        -h )
            url="https://www.github.com/"
            # delim="/"
            ;;
        -l )
            url="https://www.gitlab.com/"
            # delim="/"
            ;;
        --ssh )
            url="git@git${platform}.com:"
            # delim=":"
            ;;
        -a )
            url="https://aur.archlinux.org/"
            # delim="/"
            ;;
        * )
            repo="$1"
            ;;
    esac

    shift

done

# git clone "${url}${delim}${repo}"
git clone "${url}${repo}"
