#! /usr/bin/env bash

nw=$(connmanctl services | grep "$1")

if [[ -z $nw ]]; then
    echo "Network '$1' not found - Run 'connmanctl scan wifi' to refresh list"
    exit 1
fi

command connmanctl connect ${nw##* }
