#!/bin/bash

# by date

target_dirs=("MP_ROOT/101PNV01 PRIVATE/AVCHD/BDMV/STREAM")

dest_dir=~/files/videos

get_date () {
    echo $(stat -c %y $1 | cut -d\  -f1)
}

[[ -d "$dest_dir" ]] && mkdir -p "$dest_dir"

for dir in ${target_dirs[@]}; do
    if [[ -d "$dir" ]]; then
        for date in $(stat -c %y $dir/* | cut -d\  -f1 | uniq); do
            [[ ! -d "$date" ]] && mkdir -v -p "$dest_dir/$date"
        done

        for file in "$dir/*"; do
            folder=$(get_date $file)
            fname=$(date -r $file +%d-%m-%Y_%H:%M:%S)
            if [[ -d "$dest_dir/$folder" ]] && [[ ! -a "$dest_dir/$folder/$fname" ]]; then
                echo "${fname}.mp4" >> "$dest_dir/$folder/$folder.pls"
                ffmpeg -i "$file" -an "$dest_dir/$folder/${fname}.mp4"

            elif [[ -a "$dest_dir/$folder/$fname" ]]; then
                # echo "$file already exists at destination";
                :
            else
                echo "$file -- wtf ru doing?!!";
            fi
        done
    fi
done
