#! /usr/bin/env bash

src=$(realpath "$1")
dest=$(realpath "$2")

size () {
    sourcesize=$(du -sh "$src" | awk '{print $1}' | sed 's/[^0-9.]*//g')
    destsize=$(du -sh "$dest" | awk '{print $1}' | sed 's/[^0-9.]*//g')
}

while true; do
    size
    echo -n $(echo "scale=2; $destsize / $sourcesize * 100" | bc) 
    echo % completed
    sleep 5
done

    


