#! /usr/bin/env bash


wid=$(bspc query -N -n)

unset screenx screeny
eval $(xdpyinfo | sed -n -e 's/^ \+dimensions: \+\([0-9]\+\)x\([0-9]\+\).*/screenx=\1; screeny=\2/p')

unset windowx windowy
eval $(xwininfo -id $wid|
sed -n -e "s/^ \+Width: \+\([0-9]\+\).*/windowx=\1/p" \
       -e "s/^ \+Height: \+\([0-9]\+\).*/windowy=\1/p" )

newx=$(echo "($screenx - $windowx)/2" | bc)
newy=$(echo "($screeny - $windowy)/2" | bc)

case "$1" in
    -ul)
	    xdotool windowmove --sync $wid 3 3
	    ;;
    -ll)
	    xdotool windowmove --sync $wid 3 $(( screeny - windowy - 3 ))
	    ;;
    -ur)
	    xdotool windowmove --sync $wid $(( screenx - windowx - 3 )) 3
	    ;;
    -lr)
	    xdotool windowmove --sync $wid $(( screenx - windowx - 3 )) $(( screeny - windowy - 3 ))
	    ;;
    -c)
	    xdotool windowmove --sync $wid $newx $newy
	    ;;
esac
