#!/bin/sh

# from: http://superuser.com/questions/523194/how-to-recursively-upload-a-directory-to-a-webdav-server-through-https-from-the
DAV=https://proprefenetre.stackstorage.com/remote.php/webdav/

usage () { echo "$0 <src> <cadaver-args>*" >/dev/stderr; }
error () { echo "$1" >/dev/stderr; usage; exit 1; }

test $# '<' 2 || error "Source expected!"

src="$1"; shift;
test -r "$src" || error "Source should be a readable file or directory!"

cd "$(dirname "$src")" || exit
src="$(basename "$src")"
root="$(pwd)"
rc="$(mktemp)"
{
    find "$src" '(' -type d -a -readable ')' -printf 'mkcol "%p"\n'
    find "$src" '(' -type f -a -readable ')' -printf 'cd "%h"\nlcd "%h"\n'    \
                                             -printf 'mput "%f"\n'            \
                                             -printf 'cd -\nlcd "'"$root"'"\n'
    echo "quit"
} > "$rc"

cadaver -r "$rc" "$DAV"
rm -f "$rc"
