#! /usr/bin/python

from sys import argv
import urllib.request
from urllib.error import HTTPError

headers = {'User-Agent': "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; \
            rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7"}


def _get_response(url):
    try:
        R = urllib.request.Request(url, headers=headers)
        return urllib.request.urlopen(R).read()
        # //*[@id="tw-target-text"]/span
    except HTTPError:
        print(f"niet ok: {url}")
        raise


print(_get_response(f"https://www.google.com/search?q={argv[1]}&"))
