#! /usr/bin/env bash
# use one emacsclient frame

cli="-a -n"
if [[ -z "$DISPLAY" ]] || [[ -n "$SSH_TTY" ]]; then
    # start new frame on tty
    emacsclient -a -n -t "$@"
else
    # start new graphical frame
    emacsclient -a -n -c "$@"
fi
