#! /usr/bin/env bash
# use one emacsclient frame

check whether an Emacs server is already running
pgrep -l "^emacs$" > /dev/null

# otherwise, start Emacs server daemon
if [ $? -ne 0 ]; then
    emacs &
fi

emacsclient -a -n -c "$@"
