#! /usr/bin/env bash
# use one emacsclient frame

case $1 in
    -r|--restart)
        systemctl --user restart emacs.service
        ;;
    -s|--start)
        systemctl --user start emacs.service
        ;;
    -q|--quit)
        systemctl --user stop emacs.service
        ;;
    *)
        emacsclient --alternate-editor=/home/niels/bin/emax -s \
                    --create-frame \
                    --no-wait \
                    --socket-name="EMAX" "$@"
        ;;
esac
