#!/usr/bin/env bash

variant=$(setxkbmap -query | rg "variant:\s+(\w+)" -r '$1')

qwerty-mode () {
    setxkbmap -layout us \
              -variant altgr-intl \
              -option \
              -option terminate:ctrl_alt_bksp \
              -option ctrl:nocaps
    xmodmap ~/.Xmodmap
    notify-send -a "keyboard" "alt-intl"
}

dvorak-mode () {
    setxkbmap -layout us \
              -variant dvorak-alt-intl \
              -option \
              -option terminate:ctrl_alt_bksp \
              -option ctrl:nocaps
    xmodmap ~/.Xmodmap
    notify-send -a "keyboard" "dvorak-alt-intl"
}

case $1 in
    -q | --qwerty)
        qwerty-mode
        ;;

    -d | --dvorak)
        dvorak-mode
        ;;

    -t | --toggle)
        if [[ "$variant" = "dvorak-alt-intl" ]]; then
            qwerty-mode
        else
            dvorak-mode
        fi
        ;;

    -p | --print)
        echo "variant: $variant"
        setxkbmap -query
        ;;
esac
