#!/usr/bin/env bash

variant=$(setxkbmap -query | rg "variant:\s+(\w+)" -r '$1')

keyboard-mode () {
    setxkbmap -model pc104 \
              -layout us \
              -option \
              -option terminate:ctrl_alt_bksp \
              -option ctrl:nocaps
    sed -i -e 's/mod3/control + shift + mod1 + mod4/' ~/dotfiles/sxhkd/sxhkdrc
    pkill -USR1 -x sxhkd
    notify-send -a "keyboard" "alt-intl"
}

laptop-mode () {
    setxkbmap -model pc104 \
              -layout us \
              -variant dvorak-alt-intl \
              -option \
              -option terminate:ctrl_alt_bksp \
              -option ctrl:nocaps
    xmodmap ~/.Xmodmap
    sed -i -e 's/control + shift + mod1 + mod4/mod3/' ~/dotfiles/sxhkd/sxhkdrc
    # toggle keyboard layout
    pkill -USR1 -x sxhkd
    notify-send -a "keyboard" "dvorak-alt-intl"
}

case $1 in
    -q | --qwerty)
        keyboard-mode
        ;;

    -d | --dvorak)
        laptop-mode
        ;;

    -t | --toggle)
        if [[ "$variant" ]]; then
            keyboard-mode
        else
            laptop-mode
        fi
        ;;

    -p | --print)
        echo "variant: $variant"
        setxkbmap -query
        ;;
esac
