#!/usr/bin/env bash

id=$(xinput list | grep "AT Translated Set 2 keyboard" | awk '{print $7}' | awk -F'=' '{print $2}')
state=$(xinput list-props $id | grep "Device Enabled" | awk '{print $NF}')
layout=$(setxkbmap -query | grep "variant" | cut -d ' ' -f5 | cut -d'-' -f1)

case $1 in
    -o | --off) 
            if [ "$state" -eq 1 ]; then
                xinput disable "$id"
                notify-send -a "Keyboard" "Keyboard off"
            else
                if [ "$state" -eq 0 ]; then
                    xinput enable "$id"
                    notify-send -a "Keyboard" "Keyboard on"
                fi
            fi
            ;;

    -dv | --dvorak)  
            setxkbmap -model asus_laptop -layout us -variant dvorak-alt-intl 
            notify-send -a "Keyboard Layout" "dvorak"
            ;;
    -qw | --qwerty)
            setxkbmap -model asus_laptop -layout us -variant alt-intl 
            notify-send -a "Keyboard Layout" "qwerty"
            ;;
    -t | --test)
            echo "id:       $id"
            echo "state:    $state"
            echo "layout:   $layout"
        ;;
esac

