#!/bin/bash

tmpdir="/run/user/$UID"
lock_icon="$HOME/files/pics/lock_round-red.png"
image="$tmpdir/bg.png"

scrot "$image"
convert "$image" -scale 10% -scale 1000% -fill black -colorize 25% "$image"
[[ -f "$lock_icon" ]] && convert "$image" "$lock_icon" -gravity center -composite "$image"

i3lock -ui "$image" 
rm "$image"
