#!/usr/bin/bash


VGA=VGA1
LVDS=LVDS1

if [[ $# != 0 ]]; then
    case $1 in
        -l ) xrandr --output $VGA --rotate left;;
        -r ) xrandr --output $VGA --rotate right;;
        # this acts weird. Returning the display back to normal only works 
        # with with "mhead -n" followed by the xrandr command below ("mhead")
        -n ) xrandr --output $VGA --rotate normal;;
        -i ) xrandr --output $LVDS --auto --output $VGA --auto --left-of $LVDS;;
        -o ) xrandr --output $LVDS --auto --output $VGA --off;;

        * )
            echo "usage:"
            echo "$0 [-l | -r | -n | -i]"
            echo "-l:   rotate left"
            echo "-r:   rotate right"
            echo "-n:   back to normal"
            echo "-i:   switch primary/secondary screen"
    esac
else
    if [[ $(xrandr | grep "$VGA disconnected") ]]; then
        xrandr --output $LVDS --auto --output $VGA --off 
    else
        xrandr --output $LVDS --auto --primary --output $VGA --auto --right-of $LVDS --rotate left

    [[ -f $HOME/.fehbg ]] && . $HOME/.fehbg

    fi        
fi
