#!/bin/bash


extern=$(xrandr | grep -i "vga" | awk '{print $1}')
intern=$(xrandr | grep -i "lvds" | awk '{print $1}')

usage() {
    echo "usage:"
    echo "$(basename "$0") [option]"
    echo "  -i, --intern    use $intern only"
    echo "  -e, --extern    use $extern only"
    echo "  -b, --both:     use both"
}

ext_loc_file=/tmp/mhead_loc_file

if [ ! -f "$ext_loc_file" ]; then
    echo "left" > "$ext_loc_file"
fi

if [[ $# != 0 ]]; then
    while :; do
        case $1 in
            -t | --test ) 
                echo "LVDS: $intern"
                echo "VGA:  $extern"
                echo "VGA location: $(cat $ext_loc_file)"
                exit
                ;;
            -i | --intern )
                xrandr --output "$intern" --auto --output "$extern" --off
                break
                ;;
            -e | --extern )
                xrandr --output "$extern" --auto --output "$intern" --off
                break
                ;;
            -b | --both)
                xrandr --output "$intern" --auto --output "$extern" --auto --left-of "$intern"
                break
                ;;
            -s | --switch)
                loc=$(< $ext_loc_file)
                if [ "$loc" = left ]; then
                    xrandr --output "$intern" --auto --output "$extern" --auto --right-of "$intern"
                    echo "right" > "$ext_loc_file"
                else
                    xrandr --output "$intern" --auto --output "$extern" --auto --left-of "$intern"
                    echo "left" > "$ext_loc_file"
                fi
                break
                ;;
            -h | --help )
                usage
                exit
                ;;
            *) 
                break
        esac
    done
else
    if xrandr | grep "$extern disconnected"; then
        xrandr --output "$intern" --auto --output "$extern" --off 
    else
        xrandr --output "$extern" --auto --output "$intern" --off

    fi        
fi
