#!/bin/bash


extern=$(xrandr | grep -i "vga" | awk '{print $1}')
intern=$(xrandr | grep -i "lvds" | awk '{print $1}')

if [[ $# != 0 ]]; then
    case $1 in
        --test ) echo "$intern"
                 echo "$extern"
                 ;;

        -l ) xrandr --output "$extern" --rotate left
             ;;
        -r ) xrandr --output "$extern" --rotate right
             ;;
        # this acts weird. Returning the display back to normal only works 
        # with with "mhead -n" followed by the xrandr command below ("mhead")
        -n ) xrandr --output "$extern" --rotate normal
             ;;
        -i ) xrandr --output "$intern" --auto --output "$extern" --auto --left-of "$intern"
             ;;
        -b ) xrandr --output "$intern" --auto --primary --output "$extern" --auto --right-of "$intern"
             ;;
        -o ) xrandr --output "$intern" --auto --output "$extern" --off
             ;;
        -e ) xrandr --output "$extern" --auto --output "$intern" --off 
             ;;

        * )
            echo "usage:"
            echo "$0 [-l | -r | -n | -i]"
            echo "-l:   rotate left"
            echo "-r:   rotate right"
            echo "-n:   back to normal"
            echo "-i:   switch primary/secondary screen"
            echo "-e:   external monitor is only monitor"
            echo "-b:   use both monitors; laptop is primary"
            ;;
    esac
else
    if xrandr | grep "$extern disconnected"; then
        xrandr --output "$intern" --auto --output "$extern" --off 
    else
        xrandr --output "$extern" --auto --output "$intern" --off

    fi        
fi
