#! /usr/bin/env bash

# convert video files to mp4.

# usage: mts2mp4 <in> <out> 

(( $# < 2 )) && err "Error: files not found"

f=$(basename $1)

if [[ -d "$2" ]]; then
    d=$(readlink -f $2)
    out="$d/$in.mp4"
else
    out="$2.mp4"
fi

ffmpeg -i "$in" -an "$out"
