#!/bin/bash
# strict mode:
set -e
set -u
set -o pipefail

fn=$1
case ${fn[@]##*.} in
    "pdf") zathura "$1" & ;;
    "docx") libreoffice "$1" & ;;
    "odt") libreoffice "$1" & ;;
    *)  gvim "$1" ;;
esac

