#!/usr/bin/env bash
# https://git.zx2c4.com/password-store/tree/contrib/dmenu

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu)

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then

        printf '%s' "${password##*/}" | xclip -i -selection clipboard 
        # xdotool ignores dvorak keymap. 'k' is 'v' on a querty keyboard
        xdotool search --class --onlyvisible chromium windowfocus key ctrl+k
	pass -c "$password" 2>/dev/null
        xdotool search --class --onlyvisible chromium windowfocus key Tab
        xdotool search --class --onlyvisible chromium windowfocus key ctrl+k
else
	pass show "$password" | { read -r pass; printf %s "$pass"; } |
		xdotool type --clearmodifiers --file -
fi
