#! /usr/bin/env python

import sys
from itertools import zip_longest


def grouper(iterable, n, fillvalue=None):
    "Collect data into fixed-length chunks or blocks"
    # grouper('ABCDEFG', 3, 'x') --> ABC DEF Gxx"
    args = [iter(iterable)] * n
    return zip_longest(*args, fillvalue=fillvalue)


for p in grouper(sys.argv[1:], 2):
    print(round(float(p[0]) / float(p[1]), 3))
