#! /usr/bin/env python
# -*- coding: utf-8 -*-


from pathlib import Path
import socket
import sys

HOST, PORT = "192.168.1.2", 8001

SAVE_FILE = Path.home() / "saved_links"


def store_link(link):
    with open(SAVE_FILE, 'a') as sf:
        sf.write(f"{link}\n")


def retrieve_links():
    links = []
    with open(SAVE_FILE, 'r') as sf:
        for line in sf.readlines():
            links.append(line.strip())
    return links


def send_to_server(link):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        try:
            sock.settimeout(5)
            sock.connect((HOST, PORT))
            sock.send(bytes(link + "\n", "utf-8"))
            received = str(sock.recv(4096), "utf-8")
        except socket.error:
            store_link(link)


if __name__ == "__main__":
    
    data = sys.argv[1:]

    if SAVE_FILE.exists():
        data.extend(retrieve_links())
        SAVE_FILE.unlink()

    for l in set(data):
        send_to_server(l)

