#!/usr/bin/env bash

pic=/home/niels/files/pics/wallpaper/16ROTTERDAM2-superJumbo.jpg

# $(shuf -n 1 -e /home/niels/files/pics/wallpaper/*)
tmpf=/run/user/1000/cur_bg

echo $pic > $tmpf

hsetroot -fill $pic
