#!/bin/bash
#
# Inspired by "snippy" by "sessy" 
# (https://bbs.archlinux.org/viewtopic.php?id=71938)
#

CONFIG=${HOME}/.snippyrc

# Display the menu and get the selection
SELECTION=$(cat $CONFIG | rofi -dmenu)

if [[ ${SELECTION} ]]; then
    printf '%s' "${SELECTION}" | xclip -i -selection clipboard 
    # 'k' is 'v' on a querty keyboard
    xdotool search --class --onlyvisible chromium windowfocus key ctrl+k
fi

