#!/usr/bin/env bash

dimensions=$(xrandr | grep "*" | awk '{print $1}')
height=${dimensions#*x}
width=${dimensions%x*}

#x_corner=$(echo "scale=2; 0.25 * $width" | bc)

case $1 in
    -h ) echo $height
        ;;

    -w ) echo $width
        ;;

    * ) hsetroot -fill /home/niels/pics/wallpapers/flattened-dark-bg.png
        i3-msg 'append_layout ~/.config/i3/space.json' >/dev/null && gvims
        ;;
esac
