#! /usr/bin/env bash

wifi="$(connmanctl technologies | grep "wifi" --after-context 3 | grep "Connected" | cut -d' ' -f5)"
wlan_iface=wlp3s0
wl_ssid="$(iw $wlan_iface link | grep -i 'ssid' | cut -d ' ' -f2-)"

eth="$(connmanctl technologies | grep "ethernet" --after-context 3 | grep "Connected" | cut -d' ' -f5)"

state="$(connmanctl state | grep "State" | cut -d ' ' -f5)"

case $state in
    "online" )
        if [[ $wifi == "True" ]]; then
            echo "   $wl_ssid "
        else 
            if [[ $eth == "True" ]]; then
            echo "   online "
            fi
        fi
        ;;

    "idle")
        echo "   offline "
        ;;

esac
