#! /usr/bin/env bash



get_iface() {
    ip route | grep -Po "dev \K[[:alnum:]]+" | head -n 1
}

wlan_iface="$(iw dev | grep "Interface" | cut -d' ' -f2)"
wlan_ssid="$(iw $wlan_iface link | grep -i 'ssid' | cut -d ' ' -f2-)"

iface=$(get_iface)

case "$iface" in
    wlp*)
        if [[ -n "$wlan_ssid" ]]; then
            echo " $wlan_ssid "
        else
            echo " offline "
        fi
        ;;
    enp*)
         echo " $iface "
         ;;
    *)
        echo " Error: $iface "
        ;;
esac
