#!/usr/bin/env bash


while :; do
    DATETIME="$(date "+%a %d %b %H:%M")"

    CHARGE=""
    if [[ -z "$(acpi --battery)" ]]; then
        CHARGE="NA"
    else
        CHARGE="$(acpi --battery | grep -Eo "[0-9]{2,3}%")"
    fi

    IFACE=$(ip route | grep -Po "dev \K[[:alnum:]]+" | head -n 1)
    if [[ "$IFACE" == "wlp2s0" ]]; then
        wlan_ssid="$(iw $IFACE link | grep -i 'ssid' | cut -d ' ' -f2-)"
        if [[ -n "$wlan_ssid" ]]; then
            IFACE="$wlan_ssid"
        else
            IFACE="offline"
        fi
    fi

    SOUND=$(amixer | awk '/Mono: .*/{print $4, $NF}' | head -n 1 | tr -d ' []')
    VOL=${SOUND% *}
    MUTED=${SOUND#* }
    if [[ "$HOSTNAME" = PFN ]]; then
        LINE="S $MUTED ($VOL) | $IFACE | $CHARGE% | $DATETIME "
    else
        LINE="S $MUTED | $IFACE | $CHARGE | $DATETIME "
    fi

    echo $LINE
    sleep 1
done
