#!/bin/sh

# It is more robust to disable it by name than by ID number. The devices may be renumbered.
NAME="ETPS/2 Elantech Touchpad"
STATE=$(xinput list-props "$NAME"|grep "Device Enabled"|awk '{print $4}')

if [ $STATE -eq 1 ] ; then
    xinput disable "$NAME"
    notify-send -a "Touchpad" "Disabled"
else
    xinput enable "$NAME"
    notify-send -a "Touchpad" "Enabled"	 
fi
