#! /usr/bin/env bash

if [[ -z $(pgrep transmission-da) ]]; then
    transmission-daemon
    echo "Starting Transmission-daemon"
    sleep 5s
fi

if [[ $# -lt 1 ]]; then
    transmission-remote --add "$(xsel --clipboard)"
else
    transmission-remote --add $1
fi
