#! /usr/bin/env bash

if [[ -z $(pgrep transmission-da) ]]; then
    transmission-daemon
    echo "Starting Transmission-daemon, please hold"
    sleep 2s
    echo "tick tock ..."
    sleep 2s
    echo "not funny, is it?"
fi

transmission-remote --add "$(xsel --clipboard)"
