#!/usr/bin/env python
# -*- coding: utf-8 -*-

import subprocess
import textwrap


proc = subprocess.run(['transmission-remote', '--list'],
                      stdout=subprocess.PIPE,
                      universal_newlines=True)

for line in proc.stdout.split('\n'):
    print(textwrap.fill(line))
#     if line.startswith('Sum'):
#         _, total, _, up, down = line.split()
#         print('u: {} kb/s, d: {} kb/s'.format(up, down))


