#!/usr/bin/env bash

state=$(amixer get Master | grep -Eo "\[(on|off)\]" | grep -oE "[a-z]+")
volume=$(amixer get Master | grep -Eo "([0-9]+)%" | grep -oE "[0-9]+")

if [[ $state == 'on' ]]; then
    icon="   "
    msg="${volume}%"
else
    icon="   "
    msg="muted"
fi

echo " $icon $msg "
