#!/bin/bash
# Get the coordinates of the active window's
#    top-left corner, and the window's size.
#    This excludes the window decoration.
unset x y w h
eval $(xwininfo -id $(xdotool search --classname $(xprop | sed -n -e 's/WM_CLASS(STRING) = "\(.*\)",.*$/\1/p')) |
sed -n -e "s/^ \+Absolute upper-left X: \+\([0-9]\+\).*/x=\1/p" \
	-e "s/^ \+Absolute upper-left Y: \+\([0-9]\+\).*/y=\1/p" \
	-e "s/^ \+Width: \+\([0-9]\+\).*/w=\1/p" \
	-e "s/^ \+Height: \+\([0-9]\+\).*/h=\1/p" )
echo "upper-left x: $x"
echo "upper-left y: $y"
echo "width: $w"
echo "height: $h"
